language: cpp

compiler: 
- g++

os:
- linux
- osx

before_install:
- chmod +x ./.travis/build.sh

before_script:
- make

script:
- cd netzoo-c/panda
- make test

after_script: make clean

branches:
  only:
  - devel

after_success:
- bash <(curl -s https://codecov.io/bash)

