language: cpp

compiler: 
- g++

os:
- linux
- osx

before_install:
- chmod +x ./.travis/build.sh

before_script:
- cd netzoo-c/panda
- make
- ./PANDA -e ../../tests/ToyData/ToyExpressionData.txt -m ../../tests/ToyData/ToyMotifData.txt -o ToyOutput
- cd ../../tests/panda
- make

script:
- pwd
- ls
- ./test-panda ../ToyData/ToyOutput_FinalNetwork.pairs ../../netzoo-c/panda/ToyOutput_FinalNetwork.pairs 

after_script: make clean

after_success:
- bash <(curl -s https://codecov.io/bash)

