language: cpp

compiler: 
- g++

os:
- linux
- osx

before_install:
- chmod +x ./.travis/build.sh

script:
- cd netzoo-c/panda
- make && make test

branches:
  only:
  - devel

after_success:
- bash <(curl -s https://codecov.io/bash)

